### ISSUE TITLE
视频流接口的一个疑问

### ISSUE THREAD

**Issue by MarybethGasman** [RaymondCode/simple-demo#1]
如果用户已登录，请求没有传token，is_favorite字段的值能确定么?
如果没有登录肯定是false
![image](https://user-images.githubusercontent.com/90539473/167348617-fd3d563e-ac31-44f6-9944-7367d3ebe449.png)

**Comment by ACking-you** [comment]
我一样这里困惑，感觉应该是前端没设计完，这个视频流似乎就只有打开应用的时候或者刷新的时候请求

**Comment by liufei2606** [comment]
没登陆应该就默认没点赞吧
